CREATE TABLE [dbo].[tblUser]
(
	[UserId] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [Email] VARCHAR(200) NOT NULL, 
    [Password] VARCHAR(100) NOT NULL, 
    [FirstName] VARCHAR(100) NOT NULL, 
    [LastName] VARCHAR(100) NOT NULL, 
    [LoginId] VARCHAR(100) NOT NULL
)
