//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWDP.PlayList.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSuggestedSong
    {
        public System.Guid SuggestedSongId { get; set; }
        public string SuggestedSongTitle { get; set; }
        public string SuggestedSongArtist { get; set; }
        public string SuggestedSongAlbumTitle { get; set; }
        public string SuggestedSongImagePath { get; set; }
    }
}
